#with entry defines the main entry point of the Jac program similar to Python's if __name__ == "__main__":
#single entry block
with entry{
print("Hello, single entry block");
}

#First entry block
with entry{
    print("Hello, first entry block");
}

#Second entry block
with entry{
    print("Hello, second entry block");
}

#Third entry block
with entry {
    print("Hello, third entry block");
}
